migraciones_canal_online:
  separador: "|"
  encoding: "latin-1"
  nombres_columnas:
    CVE_MES: cve_mes
    CVE_DIA: cve_dia
    DN: dn
    CVE_ABONADO: cve_abonado
    ID_ABONADO: id_abonado
    CVE_CLIENTE: cve_cliente
    ID_CLIENTE: id_cliente
    CVE_CUENTA: cve_cuenta
    ID_PLAN: id_plan
    DES_PLAN: des_plan
    RENTA_S_IMP: renta_s_imp
    DES_MOVIMIENTO: des_movimiento
    CICLO: ciclo
    CANAL: canal
    SUB_CANAL: sub_canal
    CANAL_ONIX: canal_onix
    ESTATUS: estatus
    USUARIO: usuario
    CAPTURA: captura
    PROVEEDOR: proveedor
    NBA: nba
    NOM_CLIENTE: nom_cliente
  datatypes:
    cve_mes: str
    cve_dia: str
    dn: str
    cve_abonado: str
    id_abonado: str
    cve_cliente: str
    id_cliente: str
    cve_cuenta: str
    id_plan: str
    des_plan: str
    renta_s_imp: float64
    des_movimiento: str
    ciclo: str
    canal: str
    sub_canal: str
    canal_onix: str
    estatus: str
    usuario: str
    captura: str
    proveedor: str
    nba: str
    nom_cliente: str
  tabla_destino: tbl_migraciones_canal_online